import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className="min-h-[100dvh] flex flex-col font-sans bg-background">
        <header className="w-full bg-primary text-white flex items-center justify-center py-4 shadow-lg">
          <div className="flex items-center gap-4 w-full max-w-4xl px-4">
            <Image src="/jarfalla-logo.svg" alt="Järfälla kommun" width={120} height={40} style={{height: "40px", width: "auto"}} />
            <nav className="flex-1 flex items-center h-full justify-end">
              <ul className="flex gap-6 text-lg font-semibold items-center h-full">
                <li><Link href="/" className="hover:underline">Start</Link></li>
                <li><Link href="/praktisk-information" className="hover:underline">Praktisk information</Link></li>
                <li><Link href="/kontakt" className="hover:underline">Kontakt</Link></li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="w-full flex flex-col items-center flex-1">
          <div className="w-full max-w-4xl px-4 mt-12 pb-8">
            {children}
          </div>
        </main>
        <footer className="w-full bg-primary text-white flex items-center justify-center py-4 mt-8">
          <div className="flex items-center gap-4 w-full max-w-4xl px-4">
            <Image src="/jarfalla-logo.svg" alt="Järfälla kommun" width={80} height={30} style={{height: "30px", width: "auto"}} />
            <span className="flex-1 text-sm">Järfälla kriswebb - {new Date().getFullYear()}</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
